"""Remove evolution field from Monster model

Revision ID: 12004af821e4
Revises: a2064f306913
Create Date: 2024-07-18 10:59:28.140987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12004af821e4'
down_revision = 'a2064f306913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monster', schema=None) as batch_op:
        batch_op.drop_column('evolution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evolution', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
